name: CI

on: 
  push: 
    branches:
      - main

jobs:
  setup:
    name: setup pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Installing dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Run command linux
      run: echo "Hello GitHub Action"
